--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/brokiem/Trashcan
build-by-default: true
branches:
- master
projects:
  Trashcan:
    path: ""
    libs:
      - src: muqsit/InvMenu/InvMenu
        version: ^4.3.8
        branch: "4.0"
...
