name: TrashcanPlus
main: broki\trashcanplus\Trashcan
version: 1.0.1
api: 5.0.0
author: broki, NuhDev

permissions:
  trashcanplus.spawn:
    default: op
  trashcanplus.despawn:
    default: true
  trashcanplus.get:
    default: op
  trashcanplus.despawn.force:
    default: op
  trashcanplus.reload:
    default: op
  trashcanplus.notify:
    default: op
