name: TrashcanPlus
main: broki\trashcanplus\Trashcan
version: 1.0.0
api: 4.0.0
author: broki

permissions:
  trashcanplus.spawn:
    default: op
  trashcanplus.despawn:
    default: true
  trashcanplus.get:
    default: op
  trashcanplus.despawn.force:
    default: op
  trashcanplus.reload:
    default: op